### ISSUE TITLE
after success: coveralls error in python 3.4

### ISSUE THREAD

**Issue by r9y9** [r9y9/pysptk#6]
```
The command "nosetests --with-coverage --cover-package=pysptk -v -w tests/" exited with 0.
$ coveralls
Submitting coverage to coveralls.io...
Source file is not python pysptk/sptk
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/tokenize.py", line 375, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 24-25: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/bin/coveralls", line 9, in <module>
    load_entry_point('coveralls==0.5', 'console_scripts', 'coveralls')()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coveralls/cli.py", line 60, in main
    result = coverallz.wear()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coveralls/api.py", line 78, in wear
    json_string = self.create_report()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coveralls/api.py", line 97, in create_report
    data = self.create_data()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coveralls/api.py", line 145, in create_data
    self._data = {'source_files': self.get_coverage()}
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coveralls/api.py", line 157, in get_coverage
    return reporter.report()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coveralls/reporter.py", line 27, in report
    self.parse_file(cu, self.coverage._analyze(cu))
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coverage/control.py", line 592, in _analyze
    return Analysis(self, it)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coverage/results.py", line 22, in __init__
    exclude=self.coverage._exclude_regex('exclude')
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/coverage/parser.py", line 29, in __init__
    sourcef = open_source(self.filename)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/tokenize.py", line 438, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/tokenize.py", line 416, in detect_encoding
    encoding = find_cookie(first)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/tokenize.py", line 380, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for '/home/travis/build/r9y9/pysptk/pysptk/sptk.cpython-34m.so'
```

**Comment by r9y9** [comment]
Fixed by https://github.com/r9y9/pysptk/commit/bb074008cc6252d7e670ca55b0391aa9e0c05f00
