### ISSUE TITLE
install failed on python3.6

### ISSUE THREAD

**Issue by yulin-li** [r9y9/pysptk#80]
I got the following error while installing pysptk on python3.6. Installing numpy before pysptk could work around.

Collecting pysptk
  Downloading https://files.pythonhosted.org/packages/7c/25/4ea0932fbf0f1db42934b85011c1c825bcf57055ecde7e511f05e9fb9197/pysptk-0.1.18.tar.gz (419kB)
    100% |################################| 419kB 3.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0t3fb45w/numpy-1.20.0rc1/setup.py", line 30, in <module>
        pass
    RuntimeError: Python version >= 3.7 required.

**Comment by r9y9** [comment]
Python 3.6 won't be supported.

**Comment by r9y9** [comment]
Please use Python 3.7 or later.
