### ISSUE TITLE
theq() : determinant of the normal matrix is too small!

### ISSUE THREAD

**Issue by joan126** [r9y9/pysptk#82]
Hi, I am running mcd using pysptk for mgcep calling, error msg get below:

theq() : determinant of the normal matrix is too small!
mgcep : Error in theq() at 0th iteration!
theq() : determinant of the normal matrix is too small!
mgcep : Error in theq() at 1th iteration!
Traceback (most recent call last):
  File "MCD-DTW.py", line 56, in <module>
    mgc1 = readmgc(filename1)
  File "MCD-DTW.py", line 29, in readmgc
    mgc = pysptk.mgcep(frames, order, alpha, gamma)
  File "<decorator-gen-18>", line 2, in mgcep
  File "/home/work/anaconda3/envs/py36/lib/python3.6/site-packages/pysptk/util.py", line 75, in apply_along_last_axis
    ret = np.apply_along_axis(func, -1, *args, **kwargs)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "/home/work/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 402, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "<decorator-gen-17>", line 2, in mgcep
  File "/home/work/anaconda3/envs/py36/lib/python3.6/site-packages/pysptk/util.py", line 94, in automatic_type_conversion
    return func(*args, **kwargs).astype(dtypein)
  File "/home/work/anaconda3/envs/py36/lib/python3.6/site-packages/pysptk/sptk.py", line 729, in mgcep
    maxiter, threshold, etype, eps, min_det, itype, otype)
  File "pysptk/_sptk.pyx", line 219, in pysptk._sptk.mgcep
RuntimeError: failed to compute mgcep; error occured in theq

**Comment by joan126** [comment]
@r9y9  hi, could you help to see this issue? thanks in advance!

**Comment by r9y9** [comment]
Could you check if this happens using the original SPTK? I suppose this error is not the fault of the pysptk wrapper.￼

**Comment by joan126** [comment]
> Could you check if this happens using the original SPTK? I suppose this error is not the fault of the pysptk wrapper.￼

yes, I install pysptk using pip install pysptk==0.0.18 . I am using it to process 16000 sampling rate wav

**Comment by r9y9** [comment]
I meant http://sp-tk.sourceforge.net/. pysptk is just a wrapper around it.

**Comment by r9y9** [comment]
I am closing this. Feel free to reopen if the problem happens only for pysptk.

**Comment by huskyachao** [comment]
Hi~  I also met with the same problem. Did you solve it ?
